# -*- coding: utf-8 -*-
"""PREDIKSI GOAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNqpjc9I8Wuqs6p0IB7G_7sWffa68vf-

**Nama : Muhammad Abdul Rozak** <br>
**Nim : 221351090** <br>
**Kelas : Pagi A**

# Business Understanding

## Project Domain

## Problem Statements

## Goals

## Solution Statements

## Import data dari kaggle

# Data Understanding
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!ls ~/.kaggle

!kaggle datasets download -d mohamedhanyyy/top-football-leagues-scorers

!mkdir top-football-leagues-scorers
!unzip top-football-leagues-scorers.zip -d top-football-leagues-scorers
!ls top-football-leagues-scorers

"""# Deskripsi library yang digunakan"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

""" # Memanggil Dataset"""

df = pd.read_csv('top-football-leagues-scorers/Data.csv')

"""# Deskripsi Dataset"""

df.head()

# @title Matches_Played

from matplotlib import pyplot as plt
df['Matches_Played'].plot(kind='hist', bins=20, title='Matches_Played')
plt.gca().spines[['top', 'right',]].set_visible(False)

df.info()

sns.heatmap(df.isnull())

df.describe()

"""# Visualisasi Data"""

plt.figure(figsize=(10, 8))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True)
plt.show()

"""#Jumlah gol sesuai nama club"""

Club = df.groupby('Club').count()[['Goals']].sort_values(by='Goals',ascending=True).reset_index()
Club = Club.rename(columns={'Goals':'Goals'})

sns.barplot(x=df['Club'], y=df['Goals'], color='royalblue')

"""#Jumlah Gol"""

Club = df.groupby('Club').sum().reset_index()

plt.figure(figsize=(15,5))
sns.barplot(x= Goals['Goals'], y= Goals['Matches_Played'], color='royalblue')
plt.xticks(rotation=60)

"""# Mencari Nilai Distribusi"""

plt.figure(figsize=(15,5))
sns.distplot(df['Matches_Played'])

plt.figure(figsize=(15,5))
sns.distplot(df['Goals'])

"""# Seleksi Fitur"""

feature = ['Mins',	'Matches_Played',	'Shots',	'OnTarget',	'Year']
x = df[feature]
y = df['Goals']
x.shape, y.shape

"""# Split Data Training dan Data Testing"""

from sklearn.model_selection import train_test_split
x_train, X_test, y_train, y_test = train_test_split(x,y,random_state=70)
y_test.shape

"""# Membuat Model Regresi Linier"""

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
pred = lr.predict(X_test)

score = lr.score(X_test, y_test)
print('akurasi model regesi linier =', score)

"""#Membuat Inputan Model Regresi Linier"""

#Mins= 2071, Matches_Played=22,  Shots=37, OnTarget=26,  Year=2019
input_data = np.array([[2071,22,37,26,2019]])

prediction = lr.predict(input_data)
print('Estimasi Gol yang dihasilkan permusim :', prediction)

"""# Save Model"""

import pickle
filename = 'estimasi_jumlahgol.sav'
pickle.dump(lr,open(filename,'wb'))

"""# Evaluasi"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Memasukkan fitur dan target
feature = ['Mins', 'Matches_Played', 'Shots', 'OnTarget', 'Year']
x = df[feature]
y = df['Goals']

# Membuat model dan melatihnya
model = LinearRegression()
model.fit(x, y)

# Melakukan prediksi menggunakan model
y_pred = model.predict(x)
r_squared = r2_score(y, y_pred)

# Menampilkan R-squared
print("Nilai akurasi R-squared (R^2):", r_squared)

"""#Deployment

## Model Simulation

## Save Model
"""